name: Build and Deploy Web Component
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
   
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13'
       
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
       
      - name: Install dependencies
        run: pnpm install
     
      - name: Build component
        run: pnpm run build

      - name: Commit build files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f dist/
          git commit -m "Build for release ${GITHUB_REF#refs/tags/}"
          git push
     
      - name: Upload artifact to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/my-web-component.js
          tag_name: ${{ github.ref_name }}
          content_type: application/javascript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}