name: Build and Deploy Web Component

on:
  push:
    tags:
      - '*'  # Trigger on all git tags (e.g., 1.0, 1.1)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build component
        run: pnpm run build

      - name: Upload artifact to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/my-web-component.umd.js
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
